### PR TITLE
Remember user locale choice

### PR DESCRIPTION
**Pull request by labuladong**
Fixes https://github.com/vuepress/ecosystem/issues/253

### Before submitting the PR, please make sure you do the following 

- [x] Read the [Contributing Guidelines](https://github.com/vuepress/ecosystem/blob/main/CONTRIBUTING.md).
- [x] Provide a description in this PR that addresses **what** the PR is solving. If this PR is going to solve an existing issue, please reference the issue (e.g. `close #123`).

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New feature
- [ ] Other

### Screenshots

**Before**

**After**

### CODE REVIEW

**Comment by labuladong** [comment]
PTAL @Mister-Hope, thanks

**Comment by Mister-Hope** [comment]
I agree asking very time might be a bit annoying, but why do you think that asking only one time is reaonable?

**Comment by pengzhanbo** [comment]
I suggest adding a "Remember my choice" checkbox.

**Comment by labuladong** [comment]
> I suggest adding a "Remember my choice" checkbox.

Yes, that's a better solution, thanks. I'll close this PR.

**Pull request closed without merging**
