### PR TITLE
feat: migrate the `codePlugin` from `@vuepress/markdown` to `plugin-prismjs`

### PR DESCRIPTION
**Pull request by pengzhanbo**
### Before submitting the PR, please make sure you do the following 

- [x] Read the [Contributing Guidelines](https://github.com/vuepress/ecosystem/blob/main/CONTRIBUTING.md).
- [x] Provide a description in this PR that addresses **what** the PR is solving. If this PR is going to solve an existing issue, please reference the issue (e.g. `close #123`).

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New feature
- [ ] Other

### Description

see <https://github.com/vuepress/core/issues/1550>

### Screenshots

**Before**

**After**

### CODE REVIEW

**Comment by meteorlxy** [comment]
Please also migrate and try to improve the test cases. Code fence plugin is an important feature.

**Comment by pengzhanbo** [comment]
> Please also migrate and try to improve the test cases. Code fence plugin is an important feature.

I have a question. I need to write e2e tests for the prismjs and shiki plugins in the ecosystem. Currently, the e2e tests are using prismjs by default. If I switch between different plugins using environment variables, it will double the number of e2e tests in the GitHub actions. Do you have any other suggestions?

**Comment by pengzhanbo** [comment]
> Please also migrate and try to improve the test cases. Code fence plugin is an important feature.

Added test cases identical to the `codePlugin` in `@vuepress/core`.

**Comment by pengzhanbo** [comment]
The current PR has been merged into #137, so close this PR and continue the discussion in #137.

**Pull request closed without merging**
