### PR TITLE
chore: use eslint v9

### PR DESCRIPTION
**Pull request by Mister-Hope**

### CODE REVIEW

**Comment by Mister-Hope** [comment]
@meteorlxy Need help here.

1. There are many fail positives with `import/no-extraneous-dependencies`
2. We might need to allow `__PASCAL_CASE__` upstream
3. `declare module` is not working with eslint

@pengzhanbo Could you update the prismjs and shiki package to resolve the linter errors? I am not familar with those cdes.

**Comment by Mister-Hope** [comment]
I have already fixed all the issues I could resolve.

**Comment by meteorlxy** [comment]
1.There are many fail positives with import/no-extraneous-dependencies

Fixed. The plugins dir mapping was wrong. You only mapped to the category level, not the plugin level.

2. declare module is not working with eslint

Not only failed in eslint, but also failed in vscode. You might need more invetigation.

3. How should I bypass @typescript-eslint/no-use-before-define if 2 functions are referencing each other?

eslint-disable 😅

**Comment by Mister-Hope** [comment]
> Not only failed in eslint, but also failed in vscode.

This is weird., everything works fine at my laptop:

image

Bothe typescript language service and eslint plugin are fine in my vscode.

What about yours? @pengzhanbo (note you might need to build first)

**Comment by Mister-Hope** [comment]
Updated, this stopped working after I pull the latest commit and reload workspace, I will take further investigate

**Comment by Mister-Hope** [comment]
@meteorlxy  I am not sure, but it seems that I was not able to add additional files here: 
image

**Comment by pengzhanbo** [comment]
> What about yours

It can work normally.

**Review by pengzhanbo — APPROVED** [review]

**Pull request merged**
