### PR TITLE
feat(plugin-seo): improve `getCover`

### PR DESCRIPTION
**Pull request by pengzhanbo**
### Before submitting the PR, please make sure you do the following 

- [x] Read the [Contributing Guidelines](https://github.com/vuepress/ecosystem/blob/main/CONTRIBUTING.md).
- [x] Provide a description in this PR that addresses **what** the PR is solving. If this PR is going to solve an existing issue, please reference the issue (e.g. `close #123`).

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New feature
- [ ] Other

### Description

Currently, the `plugin-seo` assumes that the cover image configuration field is a `string`, but the actual situation may be more complex. For example, if `cover` is of an object type, the current `getCover` may encounter errors that lead to build failures.

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Can you explain why object format of cover and banner are used?

**Comment by pengzhanbo** [comment]
For example, in the [theme plume](https://theme-plume.vuejs.press/guide/blog/#%E6%96%87%E7%AB%A0%E5%B0%81%E9%9D%A2%E5%9B%BE), you can configure the cover image in more detail.

**Comment by pengzhanbo** [comment]
Implementing the `getter` in this plugin is another task that is not within the scope of this PR; this PR is solely an improvement to the default `getCover`.

**Comment by Mister-Hope** [comment]
But the main problem is that I think assuming cover is string is fine. The plugin is designed to be out of box.

If you want to provide further information about the cover, setting it with `coverSettings` or `coverStyle` should be fine, so I would rather accept a PR supporting getter directly.

**Pull request closed without merging**
